### ISSUE TITLE
Invalid ignore rules silently mis-parsed

### ISSUE THREAD

**Issue by erwinpleo** [snyk/policy#47]
- `node -v`: v12.17.0
- `npm -v`: 6.14.5
- Command run: (experienced issue when running `snyk test ...`, but see Steps to Reproduce below)

# Summary

The quirky nature of YAML can _very_ easily lead to unexpected issues, which @snyk/policy unfortunately does not report to the developer.

In this particular case it led to rules silently expiring for us.

## Sample .snyk file

```yaml
version: v1.14.0
ignore:
 FOO:
   - configstore > dot-prop:
       reason: None given
       expires: '2020-06-19T20:36:54.553Z'
 BAR:
   - configstore > dot-prop:
     reason: None given
     expires: '2020-06-19T20:36:54.553Z'
```

### Expected behaviour

Parsing fails, indicating the incorrect structure of the `BAR` ignore path.

### Actual behaviour

Parsing succeeds, and leads to the following 2 ignore rule objects:

```json
{
   "GOOD_FORMAT": [
      {
         "configstore > dot-prop": {
            "reason": "None given",
            "expires": "2020-06-19T20:36:54.553Z"
         }
      }
   ],
   "BAD_FORMAT": [
      {
         "configstore > dot-prop": null
      },
      {
         "reason": "None given"
      },
      {
         "expires": "2020-06-19T20:36:54.553Z"
      }
   ]
}
```

Note the *three* objects in the `BAD_FORMAT` rule array, vs. the *single* object (with multiple properties!) in the `GOOD_FORMAT` object.

### Steps to reproduce

1. Install `@snyk/policy`;
2. Start Node command line;
3. Type `var policy = require("@snyk/policy");` + ENTER (adjust module path as necessary);
4. Type `var rules = null; policy.load(process.cwd()).then((inRules) => {rules = inRules; console.log('got them\n');})` + ENTER and wait until the text `got them` is printed, then hit ENTER again;
5. Inspect the contents of `rules.ignore`.
